/**
 * esbuild Configuration for OpenRouter Usage Proxy CLI
 *
 * This configuration bundles the CLI entry point and server code into a single
 * CommonJS file suitable for Node.js Single Executable Application (SEA) packaging.
 *
 * Features:
 * - Bundles all TypeScript/JavaScript code into a single file
 * - Converts ESM to CommonJS for SEA compatibility
 * - Marks native modules (better-sqlite3) as external
 * - Generates source maps for debugging
 *
 * Usage:
 *   node esbuild.config.mjs
 */

import * as esbuild from 'esbuild';
import path from 'path';
import { fileURLToPath } from 'url';

// Get current file directory
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Build configuration
 */
const buildConfig = {
  // Entry point - main CLI file
  entryPoints: [path.resolve(__dirname, 'cli/index.ts')],

  // Output configuration
  outfile: path.resolve(__dirname, 'dist/bundle.cjs'),

  // Bundle all dependencies into a single file
  bundle: true,

  // CommonJS format for Node.js SEA compatibility
  // Node.js SEA requires CommonJS modules
  format: 'cjs',

  // Target Node.js platform
  platform: 'node',

  // Target Node.js 20 (minimum version for SEA and Commander v14)
  target: 'node20',

  // Mark native modules as external
  // better-sqlite3 has native bindings that cannot be bundled
  // These must be available at runtime in node_modules
  external: [
    'better-sqlite3',
  ],

  // Generate source maps for debugging
  sourcemap: true,

  // Minify for smaller bundle size (optional, can disable for debugging)
  minify: false,

  // Keep names for better stack traces
  keepNames: true,

  // Define process.env.NODE_ENV for production builds
  define: {
    'process.env.NODE_ENV': '"production"',
  },

  // Log level for build output
  logLevel: 'info',

  // Banner to identify the bundle
  banner: {
    js: `/**
 * OpenRouter Usage Proxy - Bundled CLI
 * Generated by esbuild
 *
 * This is a bundled CommonJS module for Node.js SEA packaging.
 * Native modules (better-sqlite3) must be available at runtime.
 */
`,
  },
};

/**
 * Run the build
 */
async function build() {
  try {
    process.stdout.write('[esbuild] Building CLI bundle...\n');
    process.stdout.write(`[esbuild] Entry: ${buildConfig.entryPoints[0]}\n`);
    process.stdout.write(`[esbuild] Output: ${buildConfig.outfile}\n`);

    const result = await esbuild.build(buildConfig);

    if (result.errors.length > 0) {
      process.stderr.write('[esbuild] Build failed with errors:\n');
      for (const error of result.errors) {
        process.stderr.write(`  ${error.text}\n`);
      }
      process.exit(1);
    }

    if (result.warnings.length > 0) {
      process.stdout.write('[esbuild] Build completed with warnings:\n');
      for (const warning of result.warnings) {
        process.stdout.write(`  ${warning.text}\n`);
      }
    }

    process.stdout.write('[esbuild] Build completed successfully!\n');
    process.stdout.write(`[esbuild] Bundle created at: ${buildConfig.outfile}\n`);
  } catch (error) {
    process.stderr.write(`[esbuild] Build failed: ${error.message}\n`);
    process.exit(1);
  }
}

// Run build
build();
